### PR TITLE
Minor Fixes

### PR DESCRIPTION
**Pull request by kingthorin**
Tweak capitalization of client-side to be more consistent, remove a few double spaces, fix one use of "of for".

### CODE REVIEW

**Comment by davewichers** [comment]
Hey, thanks for these edits. But capitalizing Client-Side this way is on purpose, especially in the risk category titles. Can you revert that part of your changes? The rest look good. Thx

**Comment by kingthorin** [comment]
I was just going for consistency.

Happy to tweak it further. Just so I'm clear you want all occurrences to have capitals on both words?

**Comment by davewichers** [comment]
If it was capitalized before, yes. If it was not capitalized before then both can stay lowercase.

**Comment by kingthorin** [comment]
Thanks, will get this updated.

**Comment by kingthorin** [comment]
Tweaked as requested.

**Pull request merged**
